# Майнор "Интеллектуальный анализ данных", Введение в Анализ данных (ВШЭ)
## Домашнее задание №1

__Дата выдачи__: 28.01.2016

__Дедлайн__: 23:59 10.01.2016

Задание состоит в том, чтобы дописать в этом ipython notebook тело для всех функций, чтобы они работали так, как указано в формулировке. 

### Не нужно создавать свои функции с другими названиями!
Точнее, ответ должна выдавать именно та функция, которая указана в задании. Промежуточные функции создавать, конечно, можно.

Готовый файл нужно переименовать в формате iad16\_SnapeS.ipynb (заменив фамилию «Snape» и первую букву имени «S» на свои) и прислать на [hse.minor.dm+16@gmail.com](hse.minor.dm+16@gmail.com), указав в теме «[HW1] SnapeS».

Мы настоятельно рекомендуем выполнять задание на своем компьютере. Для этого лучше всего создать отдельную папку, скопировать туда этот notebook, открыть консоль (например, в Windows8: Shift + правая кнопка мыши, выбрать "Открыть → Окно команд") и написать jupiter notebook. Тогда вы всегда будете знать, где находятся ваши файлы.

При выполнении на сервере не гарантируется его стабильная работа, и ваш код смогут видеть другие студенты. 

На всякий случай напоминаем, что списывать нехорошо. За это будет <s>выпорот</s> сурово наказан и тот, кто списал, и тот, кто у кого списали. Но надеемся, что таких случаев не будет

Если формулировка задания не ясна — пишите на почту курса или семинаристам лично. Мы с радостью поможем разобраться.

Непонятные термины рекомендуем гуглить :) 

А вот решения гуглить не рекомендуем: задания не очень сложные, и сделаны они в первую очередь для того, чтобы вы освоились с numpy и pandas. Без этого дальше изучать курс будет сложно.

__Каждое выполненное задание дает 1 балл.__

При решении задач нельзя пользоваться циклами и рекурсией.

In [3]:
import numpy as np

# во всех задачах запрещается использовать циклы и рекурсию!

__№1__.  Написать функцию, которая берет на вход прямоугольную матрицу $A$ размера m x n и превращает каждый ее столбец в дискретное распределение с помощью применения функции _softmax_:

$\text{softmax}(a_j) = \frac {\exp (a_j)}{\sum_i \exp(a_i)}$, где a --- столбец матрицы $A$.

Таким образом, в матрице, возвращенной функцией, сумма каждого столбца матрицы должна быть равна 1.

In [7]:
#Пример

Example
Input:
[[0 1]
 [1 2]]
Output:
[[ 0.26894142  0.26894142]
 [ 0.73105858  0.73105858]]


In [6]:
def compute_softmax(A):
    exp_A = np.exp(A)
    sum_exp_A = exp_A.sum(axis = 0)
    return exp_A / sum_exp_A

In [9]:
A = np.array([[0,1], [1, 2]])
compute_softmax(A)

array([[ 0.26894142,  0.26894142],
       [ 0.73105858,  0.73105858]])

__№2__. Напишите функцию, принимающую на вход матрицу X и два массива i и j одинаковой длины n и возвращающую вектор np.array, состоящий из последовательности элементов [X[i[0], j[0]], X[i[1], j[1]], ..., X[i[n-1], j[n-1]]].

In [11]:
#Пример

Example
Input:
X = [[0 1]
 [1 2]]
i =  [0 0] j =  [0 1]
Output:
0 1


In [4]:
def choose_elems(X, i, j):
    return X[i, j]

In [5]:
X = np.array([[0, 1], [1, 2]])
i = np.array([0, 0])
j = np.array([0, 1])
choose_elems(X, i, j)

array([0, 1])

__№3__. Написать функцию, которая берет на вход матрицу A размера m x n, вектор b длины m и вектор c длины n и возвращает матрицу, составленную из блоков:

$\begin{pmatrix} A & b \\  c^T& 0 \end{pmatrix}$ = 

$\begin{pmatrix} a_{00} & a_{01} & \dots &a_{0,n-1} & b_0 \\ 
a_{10} & a_{11} & \dots &a_{1,n-1} & b_1 \\
 &&\dots& \\
a_{m-1,0} & a_{m-1,1} & \dots &a_{m-1,n-1} & b_{m-1} \\ 
c_0 & c_1 & \dots & c_{n-1 }& 0 \end{pmatrix}$

Будем считать, что матрица A может быть очень большой, поэтому выделять дополнительную память размера, сопоставимого с размером матрицы, нельзя.

In [12]:
#Пример

Example
Input:
A = [[0 1]
 [1 2]]
b =  [8 9] c =  [7 3]
Output:
[[0 1 8]
 [1 2 9]
 [7 3 0]]


In [6]:
def construct_matrix(A, b, c):
    b = b[:, np.newaxis]
    c = np.append(c,[0])
    A = np.hstack((A, b))
    A = np.vstack((A, c))
    return A

In [7]:
A = np.array([[0, 1], [1, 2]])
b = np.array([8, 9])
c = np.array([7, 3])
construct_matrix(A, b, c)

array([[0, 1, 8],
       [1, 2, 9],
       [7, 3, 0]])

__№4__. Даны две небольшие бинарные матрицы $A$ размера $m \times n$ и $B$ размера $n \times k$. 
Написать функцию, возвращающую матрицу $C$ такую, что

$C_{ij} = \&_{s=1}^n (A_{is} \lor B_{sj})$.

Здесь $\&$ означает логическое умножение (and), а $\lor$ — дизъюнкцию (or).

In [14]:
#Пример

Example
Input:
A = [[False  True]
 [ True False]]
Input:
B = [[ True False]
 [False  True]]
Output:
[[ True False]
 [False  True]]


In [ ]:
def perform_logical_computation(A, B):

__№5__. Напишите функцию, принимающую на вход np.array размера n и возвращающую матрицу размера n + 1 x n + 1, у которой над главной даигональю стоят элементы массива (остальные элементы должны быть нулевыми). 

In [15]:
#Пример

Example
Input:
[[1 2]]
Output:
[[0 1 0]
 [0 0 2]
 [0 0 0]]


In [8]:
def above_diagonal(x):
    a = np.zeros((len(x)+1, len(x)+1))
    row = np.arange(len(x))
    column = np.arange(1, len(x) + 1)
    a[row,column]= x
    return a

In [11]:
x = np.array([1, 2])
above_diagonal(x)

array([[ 0.,  1.,  0.],
       [ 0.,  0.,  2.],
       [ 0.,  0.,  0.]])

__№6__. Дана матрица объекты-признаки X размера n x m. Посчитать (квадратную) матрицу попарных корреляций между признаками C:

$C_{ij} = cor_{ij} = \frac {cov_{ij}}{\sqrt{cov_{ii}cov_{jj}}}$ 

$cov_{ij} = cov(X_i, X_j), \quad i,j = 0, \dots, m-1.$

$cov(\{x_0, \dots, x_{n-1}\}, \{y_0, \dots, y_{n-1}\}) = \frac 1 {n-1} \sum_{i=0} ^ {n-1} (x_i-\bar x) (y_i - \bar y)$.

$\bar x = mean(\{x_0, \dots, x_{n-1}\}) = \frac 1 n \sum_{i=0} ^ {n-1} x_i$

Нельзя использовать функции np.cov, np.corrcoef, np.correlate (их можно использовать для проверки правильности ответа)


In [ ]:
def compute_corr_matrix(X):
    

__№7__. Дан массив X (размерность неизвестна). Заменить все элементы, кратные 3, которые больше 0 и меньше 100, на среднее значение по массиву.

In [19]:
#Пример

Example
Input:
[[14 11 10  0 12]
 [ 9  4 13  8  3]
 [ 6 14 13  5  5]
 [ 8  1  6  7 12]]
Output:
[[14 11 10  0  8]
 [ 8  4 13  8  8]
 [ 8 14 13  5  5]
 [ 8  1  8  7  8]]


In [12]:
def change_value(A):
    mean = np.sum(A)/A.size
    A[np.logical_and(A % 3 == 0, A > 0, A < 100)] = mean
    return A

In [13]:
A = np.array([[14, 11, 10,  0, 12], [ 9,  4, 13,  8,  3], [ 6, 14, 13,  5,  5], [ 8,  1,  6,  7, 12]])
change_value(A)

array([[14, 11, 10,  0,  8],
       [ 8,  4, 13,  8,  8],
       [ 8, 14, 13,  5,  5],
       [ 8,  1,  8,  7,  8]])

In [3]:
import pandas as pd

Для выполнения заданий по pandas понадобится файл _countries.csv_: [https://goo.gl/AQqxaR](https://goo.gl/AQqxaR) --- тут его нужно скачать! Чтобы загрузить файл в jupiter, на странице с ноутбуками нажмите Upload, найдите на компьютере файл, снов анажмите upload.

In [4]:
#Загрузите данные в notebook:
df = pd.read_csv("countries.csv", sep=";")

__№8__. Напишите функцию, которая берет на вход датафрейм pandas со считанными данными и возвращает ответ на следующий вопрос (строка).

Найдите страну, у которой наибольшее ВВП среди стран площадью меньше 200 или население меньше 10000 (или — не исключающее).

In [16]:
def find_country(df):
    view1 = df[['Country' ,'Area(sq km)', 'Population', 'GDP']]
    mask1 = ( (df['Area(sq km)'] < 200) | (df['Population'] < 10000) )
    view1 = view1[mask1]
    mask2 = view1['GDP']==view1['GDP'].max()
    return view1[mask2]

In [17]:
find_country(df)

Country  Area(sq km)  Population         GDP
145   Macau           25      449198  9100000000

__№9__.  Напишите функцию, которая берет на вход датафрейм pandas и возвращает датафрейм, в котором все пропуски заменены на среднее значение по столбцу. 

_Подсказка_: используйте функцию pandas.fillna()

In [18]:
def fill_na(df):
    return df.fillna(df.mean())

In [19]:
fill_na(df).head()

Country  Area(sq km)  Birth rate(births/1000 population)  \
0     Afghanistan       647500                           47.020000   
1        Akrotiri          123                           22.146667   
2         Albania        28748                           15.080000   
3         Algeria      2381740                           17.130000   
4  American Samoa          199                           23.130000   

   Current account balance  Death rate(deaths/1000 population)  \
0            -8.473897e+08                           20.750000   
1            -8.473897e+08                            9.374267   
2            -5.040000e+08                            5.120000   
3             1.190000e+10                            4.600000   
4            -8.473897e+08                            3.330000   

   Debt - external  Electricity - consumption(kWh)  \
0     8.000000e+09                    6.522000e+08   
1     6.317084e+10                    8.070919e+10   
2     1.410000e+09                    6.760000e+09   
3     2.190000e+10                    2.361000e+10   
4     6.317084e+10                    1.209000e+08   

   Electricity - production(kWh)       Exports           GDP  \
0                   5.400000e+08  4.460000e+08  2.150000e+10   
1                   8.849167e+10  4.432637e+10  2.925614e+11   
2                   5.680000e+09  5.524000e+08  1.746000e+10   
3                   2.576000e+10  3.216000e+10  2.123000e+11   
4                   1.300000e+08  3.000000e+07  5.000000e+08   

           ...           Oil - production(bbl/day)  \
0          ...                            0.000000   
1          ...                       371043.542453   
2          ...                         2000.000000   
3          ...                      1200000.000000   
4          ...                            0.000000   

   Oil - proved reserves(bbl)       Population  Public debt(% of GDP)  \
0                0.000000e+00  29928987.000000              55.896296   
1                1.416887e+10  29004941.184874              55.896296   
2                1.855000e+08   3563112.000000              55.896296   
3                1.187000e+10  32531853.000000              37.400000   
4                1.416887e+10     57881.000000              55.896296   

   Railways(km)  Reserves of foreign exchange & gold  \
0  10217.246269                         2.599825e+10   
1  10217.246269                         2.599825e+10   
2    447.000000                         1.206000e+09   
3   3973.000000                         4.355000e+10   
4  10217.246269                         2.599825e+10   

   Telephones - main lines in use  Telephones - mobile cellular  \
0                    33100.000000                  15000.000000   
1                  5998770.193966                7331345.657895   
2                   255000.000000                1100000.000000   
3                  2199600.000000                1447310.000000   
4                    15000.000000                   2377.000000   

   Total fertility rate(children born/woman)  Unemployment rate(%)  
0                                   6.750000             15.254688  
1                                   2.937778             15.254688  
2                                   2.040000             14.800000  
3                                   1.920000             25.400000  
4                                   3.250000              6.000000  

[5 rows x 45 columns]

__№10__.  Напишите функцию, которая берет на вход датафрейм pandas и число и возвращает ответ на вопрос (строка):

В какой стране ВВП (GDP) наиболее близок к указанной величине?

In [20]:
def compare_GDP(df, gdp):
    diff = abs(gdp - df['GDP'])
    mask3 = diff==diff.min()
    return df[mask3]

In [25]:
gdp = 25600000
compare_GDP(df, gdp)

Country  Area(sq km)  Birth rate(births/1000 population)  \
165  Montserrat          102                               17.56   

     Current account balance  Death rate(deaths/1000 population)  \
165                      NaN                                7.17   

     Debt - external  Electricity - consumption(kWh)  \
165          8900000                         1674000   

     Electricity - production(kWh)  Exports       GDP          ...           \
165                        1800000   700000  29000000          ...            

     Oil - production(bbl/day)  Oil - proved reserves(bbl)  Population  \
165                          0                         NaN        9341   

     Public debt(% of GDP)  Railways(km)  Reserves of foreign exchange & gold  \
165                    NaN           NaN                                  NaN   

     Telephones - main lines in use  Telephones - mobile cellular  \
165                             NaN                            70   

     Total fertility rate(children born/woman)  Unemployment rate(%)  
165                                       1.78                     6  

[1 rows x 45 columns]

__№11__. __(Дополнительный). За выполнение этого задания можно получить +1 балл к общей сумме баллов (к 10)!__

Напишите функцию, которая берет на вход датафрейм pandas со считанными данными и возвращает датафрейм с двумя колонками: буква алфавита и значение ВВП, усреднённое по всем странам, начинающимся с данной буквы.

Для решения задачи может понадобиться функция pandas.groupby, которую вы не успели пройти на семинаре. Поэтому задача и дополнительная.

In [26]:
def compute_means_by_letters(df):
    country_n = df.groupby(df["Country"].str[:1])
    return country_n['GDP'].mean()

In [27]:
compute_means_by_letters(df)

Country
#    1.165000e+13
A    1.195994e+11
B    1.210610e+11
C    4.591804e+11
D    5.777075e+10
E    5.975925e+10
F    2.715113e+11
G    1.621848e+11
H    1.036600e+11
I    8.283341e+11
J    9.463075e+11
K    1.665191e+11
L    1.958222e+10
M    6.833354e+10
N    7.424858e+10
O    3.809000e+10
P    1.716514e+11
Q    1.949000e+10
R    3.986250e+11
S    1.025396e+11
T    1.354214e+11
U    2.004431e+12
V    9.387000e+10
W    9.300000e+08
Y    1.625000e+10
Z    1.688950e+10
Name: GDP, dtype: float64